[wokwi]
version = 1
firmware = ".tools/wokwi/pendulum/pendulum.ino.hex"
elf = ".tools/wokwi/pendulum/pendulum.ino.elf"

[[chip]]
name = "ina219"
binary = "chips/ina219.chip.wasm"

[[chip]]
name = "tsl2591"
binary = "chips/tsl2591.chip.wasm"
