import type { Recipe, Sensor } from '@/schema'
import { phase5BehaviorSpecById, type Phase5BehaviorSpec, type ScenarioStep } from './behaviorSpecs'
import { buildDiagram, type Diagram } from './buildDiagram'
import type { EligiblePhase5Simulation } from './phase5SimulationRegistry'

export const PHASE5_WOKWI_ROOT = 'wokwi/phase5'
export const PHASE5_WOKWI_MANIFEST_VERSION = 1

const CUSTOM_CHIP_BY_PART_TYPE: Readonly<Record<string, string>> = {
  'chip-bme280': 'bme280',
  'chip-ina219': 'ina219',
  'chip-tsl2591': 'tsl2591',
}

export interface Phase5WokwiProject {
  id: string
  path: string
  timeoutMs: number
  scenario: string
  command: string
  diagram: Diagram
  sketch: string
  chips: string[]
  /** Present when the run is judged on sensor behaviour, not just boot. */
  behavior?: Phase5BehaviorSpec
}

export interface Phase5WokwiManifest {
  version: typeof PHASE5_WOKWI_MANIFEST_VERSION
  generatedFrom: 'phase5SimulationRegistry'
  projectCount: number
  exclusions: string[]
  projects: Array<Pick<
    Phase5WokwiProject,
    'id' | 'path' | 'timeoutMs' | 'scenario' | 'command' | 'chips'
  > & {
    kind: 'behavior' | 'smoke'
    /**
     * Changes whenever anything that decides this project's Wokwi verdict
     * changes: sketch, circuit, scenario, or behaviour expectations. PR runs
     * compare it with the base branch to simulate only the recipes that moved.
     */
    fingerprint: string
  }>
}

function instrumentSketch(recipeId: string, sketch: string): string {
  const serialBegin = /Serial\.begin\(([^;]+)\);/
  if (!serialBegin.test(sketch)) {
    throw new Error(`Phase 5 Wokwi generation: recipe "${recipeId}" has no Serial.begin marker`)
  }
  return `${sketch.trimEnd().replace(
    serialBegin,
    `Serial.begin($1);\n  Serial.println("# PHASE5_READY:${recipeId}");`,
  )}\n`
}

export function buildPhase5WokwiProjects(
  entries: EligiblePhase5Simulation[],
  recipes: readonly Recipe[],
  sensors: Sensor[],
  root: string = PHASE5_WOKWI_ROOT,
): Phase5WokwiProject[] {
  const recipesById = new Map(recipes.map((recipe) => [recipe.id, recipe]))

  return entries.map((entry) => {
    const recipe = recipesById.get(entry.recipeId)
    if (!recipe) {
      throw new Error(`Phase 5 Wokwi generation: recipe "${entry.recipeId}" was not found`)
    }

    const behavior = phase5BehaviorSpecById.get(recipe.id)
    const path = `${root}/${entry.recipeId}`
    const timeoutMs = behavior?.timeoutMs ?? entry.timeoutMs
    const scenario = 'scenario.test.yaml'
    const diagram = buildDiagram(recipe, sensors)
    const chips = [...new Set(
      diagram.parts
        .map((part) => CUSTOM_CHIP_BY_PART_TYPE[part.type])
        .filter((chip): chip is string => chip !== undefined),
    )].sort()

    return {
      id: entry.recipeId,
      path,
      timeoutMs,
      scenario,
      command: `wokwi-cli ${path} --scenario ${scenario} --timeout ${timeoutMs}`,
      diagram,
      // A behaviour run must exercise exactly what the student uploads.
      sketch: behavior ? recipe.sketch.trimEnd() + '\n' : instrumentSketch(recipe.id, recipe.sketch),
      chips,
      ...(behavior ? { behavior } : {}),
    }
  })
}

export function renderPhase5WokwiToml(project: Phase5WokwiProject): string {
  const chips = project.chips.map((chip) => [
    '',
    '[[chip]]',
    `name = "${chip}"`,
    `binary = "${chip}.chip.wasm"`,
  ].join('\n')).join('\n')

  return `${[
    '# Generated by scripts/generate-phase5-wokwi.ts. Do not edit.',
    '[wokwi]',
    'version = 1',
    'firmware = "firmware.hex"',
    'elf = "firmware.elf"',
    chips,
  ].join('\n').trimEnd()}\n`
}

function yamlString(value: string): string {
  return JSON.stringify(value)
}

function renderStep(step: ScenarioStep): string[] {
  if ('set' in step) {
    return [
      '  - set-control:',
      `      part-id: ${step.set.partId}`,
      `      control: ${step.set.control}`,
      `      value: ${step.set.value}`,
    ]
  }
  if ('waitSerial' in step) return [`  - wait-serial: ${yamlString(step.waitSerial)}`]
  if ('delayMs' in step) return [`  - delay: ${step.delayMs}ms`]
  return [
    '  - expect-pin:',
    `      part-id: ${step.expectPin.partId}`,
    `      pin: ${yamlString(step.expectPin.pin)}`,
    `      value: ${step.expectPin.value}`,
  ]
}

function renderBehaviorScenario(id: string, spec: Phase5BehaviorSpec): string {
  const steps: ScenarioStep[] = [
    { waitSerial: spec.header },
    ...spec.phases.flatMap((phase) => phase.steps),
    ...(spec.finalSteps ?? []),
  ]
  return [
    `name: Phase 5 behavior - ${id}`,
    'version: 1',
    'author: phase5-generator',
    'steps:',
    ...steps.flatMap(renderStep),
    '',
  ].join('\n')
}

export function renderPhase5Scenario(project: Phase5WokwiProject): string {
  if (project.behavior) return renderBehaviorScenario(project.id, project.behavior)
  return [
    `name: Phase 5 deterministic smoke - ${project.id}`,
    'version: 1',
    'author: phase5-generator',
    'steps:',
    `  - wait-serial: "# PHASE5_READY:${project.id}"`,
    '',
  ].join('\n')
}

function fnv1a(text: string, seed: number): string {
  let hash = seed
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index)
    hash = Math.imul(hash, 0x01000193)
  }
  return (hash >>> 0).toString(16).padStart(8, '0')
}

/** Spec as text, with derived expectations and row checks reduced to their source. */
function serializeSpec(spec: Phase5BehaviorSpec | undefined): string {
  return JSON.stringify(spec ?? null, (_key, value: unknown) =>
    typeof value === 'function' ? value.toString() : value)
}

export function phase5ProjectFingerprint(project: Phase5WokwiProject): string {
  const text = [
    project.sketch,
    JSON.stringify(project.diagram),
    renderPhase5Scenario(project),
    String(project.timeoutMs),
    serializeSpec(project.behavior),
  ].join('\u0000')
  return fnv1a(text, 0x811c9dc5) + fnv1a(text, 0x01000193)
}

export function buildPhase5WokwiManifest(
  projects: Phase5WokwiProject[],
  exclusions: string[],
): Phase5WokwiManifest {
  return {
    version: PHASE5_WOKWI_MANIFEST_VERSION,
    generatedFrom: 'phase5SimulationRegistry',
    projectCount: projects.length,
    exclusions: [...exclusions],
    projects: projects.map((project) => ({
      id: project.id,
      path: project.path,
      kind: project.behavior ? 'behavior' : 'smoke',
      timeoutMs: project.timeoutMs,
      scenario: project.scenario,
      command: project.command,
      chips: project.chips,
      fingerprint: phase5ProjectFingerprint(project),
    })),
  }
}
